main: dev.aretzera.first.first
name: first
version: 1.0.1
api-version: '1.20'
author: [Aretzera]
permissions:
  first.view:
    description: Allows the user to view the death log
    default: op

commands:
  deathlog:
    description: View the death log
    usage: /deathlog
    permission: first.view